auto: true

#markdown: rdiscount
highlighter: 'pygments'
#paginate: 8
permalink: /:title

title: Double Vector
url: http://dvector89.github.io
feed: /atom.xml
author_info: <a href="http://dvector89.github.io/">Dvector89</a>
